add enablerepo=extras for centos (#378)
In order to avoid following error:
Error: Package: centos-release-scl-2-2.el7.centos.noarch (devtools)
           Requires: centos-release-scl-rh
changed to --enablerepo=extras