Use new protobuf API instead of deprecated one (#4895)
* Use new protobuf API instead of deprecated one

This fixes compiler failures like

  error: ‘int google::protobuf::MessageLite::ByteSize() const’ is deprecated: Please use ByteSizeLong() instead [-Werror=deprecated-declarations]

* Use the right type returned by ProtoBuf ByteSizeLong()

* Replace remaining deprecated ProtoBuf ByteSize() by ByteSizeLong()

* ProtoBuf API has a safer API starting with version 3.6

According to https://github.com/eddelbuettel/rprotobuf/issues/70 it
looks like the problem is more complex as `protoc` was changed with
the safer behavior starting with version 3.6.
https://github.com/protocolbuffers/protobuf/blob/master/CHANGES.txt
Thus, using the 2 versions according to the version of the ProtoBuf used.